import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import { Roboto } from 'next/font/google';


const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-roboto',
});

export const metadata = {
    title: "Rythem Dhamija | Portfolio",
    keywords: [
        "Portfolio",
        "Web Development",
        "Frontend Developer",
        "React Developer",
        "Next.js Developer",
        "JavaScript Developer",
    ],
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="dark">
            <body className="relative min-h-screen bg-neutral-950 text-neutral-content font-[roboto]">
                <header className="fixed top-0 z-50 bg-transparent w-full">
                    <Navbar />
                </header>

                {children}

            </body>
        </html>
    );
}
